version: '3.8'

services:
  catalog:
    image: catalog
    build:
      context: ../
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    container_name: catalog
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_HTTP_PORT=5000
    networks:
      - dev-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: PlaygroundDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-net

volumes:
  postgres-data:

networks:
  dev-net:
