version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: PlaygroundDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-net

volumes:
  postgres-data:

networks:
  dev-net: